### ISSUE TITLE
isUrl & nette 2.3

### ISSUE THREAD

**Issue by Keeehi** [Kdyby/Google#12]
Nová verze nette nejspíše změnila způsob jak pracuje s konfiguračními soubory. Nevím jestli je to BC break nové verze, nebo si to má hlídat Kdyby/Google nicméně vznikl problém
```neon
google:
    returnUri: "Server:googleLogin"(do=googleLogin-response)
```
A výsledkem je
```php
Warning
preg_match() expects parameter 2 to be string, object given
// in Kdyby/Google/DI/GoogleExtension.php:164
```
Jako druhý argument se totiž do metody předá
```php
Nette\DI\Statement #01
    entity private => "Server:googleLogin"
    arguments => array (1)
        do => "googleLogin-response"
```
Když se v konfiguraci odmaže ten signál, tak už to projde. Problém bude zase ale při návratu od goolu.

**Comment by fprochazka** [comment]
@Keeehi thank you for reporting, can you please verify now that it's fixed?

**Comment by Keeehi** [comment]
@fprochazka Sure. It works. dev-master version installed trough composer. Thanks for quick fix.
