### ISSUE TITLE
Support for dynamical pages

### ISSUE THREAD

**Issue by akadlec** [Kdyby/Google#2]
Is there a plan to support google oauth for dynamical pages? I want to add oauth to comments and the return url is different for each item where comments are created. And in that case, google refuse this dynamicaly generated return url.

**Comment by ovalek** [comment]
Maybe it is possible to pass some parameters to google and retrieve them afterwards, see http://stackoverflow.com/a/7722099/1102219
That should make possible to pass the backlink hash (from presenter storeRequest()) throughout the login process, without storing it in a session.
